 window.onload = function() {
  var text = getJSON();
  var obj = JSON.parse(text);
  var type = obj.docSentiment.type;
  if(type == "negative"){
    document.getElementById("demo").innerHTML = "This Website Contains Bad Vibes Sun -- Proceed With Caution"
  }
  else{
    document.getElementById("demo").innerHTML =
    obj.docSentiment.type;
  }
  setTimeout( function () { window.close(); }, 2000);

};

function badVibes(activeFlag){

}

function getJSON(){
  var test = '{"status": "OK","warningMessage": "truncated-oversized-html-content","usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html","url": "https://www.reddit.com/r/grilledcheese/comments/2or1p3/you_people_make_me_sick/","totalTransactions": "1","language": "english","docSentiment": {"mixed": "1","score": "-0.25463","type": "negative"}}';
  return test;
}
